imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

    # doctrine
    - { resource: doctrine/doctrine.yml }
    - { resource: doctrine/doctrine_migrations.yml }

    # fos
    - { resource: fos/fos_rest.yml }

    # sonata
    - { resource: sonata/admin.yml }
    - { resource: sonata/media.yml }

    # knp
    - { resource: knp/knp_paginator.yml }

    # rabbitmqbundle
    - { resource: rabbitmq/old_sound_rabbit_mq.yml }

    # bundles
    - { resource: "@AppBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@ArticleBundle/Resources/config/services.yml" }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Assetic configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    filters:
        cssrewrite: ~
    bundles:
        - OhGoogleMapFormTypeBundle

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        admin_skin: skin-blue
    form:
        resources:
            - 'bootstrap_3_layout.html.twig'
            - 'SonataCoreBundle:Form:datepicker.html.twig'
            - 'SonataMediaBundle:Form:media_widgets.html.twig'
            - 'OhGoogleMapFormTypeBundle:Form:fields.html.twig'
            - 'AppBundle:Form:fields.html.twig'

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

jms_serializer:
    property_naming:
        separator: _
        lower_case: true
