admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"

mobile:
    resource:   routing_mobile.yml
    prefix:     /api/v1
    defaults:  { _format: json }

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin