# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.exception.listener:
        class: AppBundle\EventListener\ExceptionListener
        arguments: ['@logger']
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    app.request.listener:
        class: AppBundle\EventListener\RequestListener
        arguments: ['@logger']
        tags:
            - { name: kernel.event_listener, event: kernel.request }
