services:
    user.manager.user:
        class: UserBundle\Entity\Manager\UserManager
        arguments: ['UserBundle\Entity\User', '@doctrine']

    user.manager.device:
        class: UserBundle\Entity\Manager\DeviceManager
        arguments: ['UserBundle\Entity\Device', '@doctrine']

    user.manager.access_token:
        class: UserBundle\Entity\Manager\AccessTokenManager
        arguments: ['UserBundle\Entity\AccessToken', '@doctrine']

    user.manager.phone:
        class: UserBundle\Entity\Manager\PhoneManager
        arguments: ['UserBundle\Entity\Phone', '@doctrine']

    user.handler.user:
        class: UserBundle\Handler\UserHandler
        arguments: ["@user.manager.user", "@app.manager.city", "@user.manager.access_token"]

    user.handler.auth:
        class: UserBundle\Handler\AuthHandler
        arguments: ["@user.manager.user", "@user.manager.device", "@user.manager.access_token", "@user.handler.user", "@user.manager.phone", "@event_dispatcher"]
