hautelook_alice:
    db_drivers:
        orm: ~          # Enable Doctrine ORM if is registered
    locale: ru_RU
    seed: 1             # A seed to make sure faker generates data consistently across runs, set to null to disable
    persist_once: false # Only persist objects once if multiple files are passed
    loading_limit: 5    # Maximum number of time the loader will try to load the files passed
